### ISSUE TITLE
Near-future roadmap

### ISSUE THREAD

**Issue by ardecvz** [k0kubun/karabiner-dsl#9]
Takashi, you've proposed a good and simple solution in #8 which I didn't consider (shame on me) so I think it's nice to scratch a short plan before any new code:
- [ ] Now, in order to check for gem's updates you have to visit github as `gem` doesn't have an easy to use `outdated` command or notification system.

So I propose to include a new version availability check (such as in [Travis CLI](https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/command.rb#L140) or heroku's one). It allows to warn users about new shiny features they need hardly :) The proposed update warning would be much simpler than in Travis - just check the github's release api url non-blockingly in other thread at at **every** start of the utility. For rare-to-use gem like this one it shouldn't introduce any significant overhead and should maximize probability to notify users.
- [ ] Allow more AVAILABLE_PROPERTIES in items (for example, `lastpressedphysicalkey_only`).

In my opinion, it's much better to pass **any** user defined property to the underlying xml node and warn to stdout about unrecognized ones which aren't included in AVAILABLE_PROPERTIES in order to fight with mistypes. Honestly, do it also for similar maps with predefined things as a future-proof solution.

- [ ] Rework remap DSL.

Right now, it accepts only simple `key to key` remaps. It's not sufficient even for basic things supported in Karabiner such as holding or double press combinations (and they're great). So rework `remap` DSL to be blockish:
```
item 'Change 3 to X' do
  remap 'Ctrl-3', to: '3'
  remap '3' do
    press to: 'x'
    holding to: '3'
  end
end
```
or
      item "Command+A to Command+B" do
        remap "Cmd-A" do
          press to: "Cmd-B"
          holding to: "Cmd-D"
        end
      end
It looks more flexible and extendable .

**Comment by ardecvz** [comment]
There's a small update in the roadmap - just to warn you if you're reading it in e-mail.

**Comment by k0kubun** [comment]
OK. Now I added you to collaborators. You have push access to this repository. Since I now use Linux mainly, I have less time to maintain this.

If you want to release karabiner gem by yourself, please create rubygems account and notify me your email address.

**Comment by ardecvz** [comment]
I'm in, thank you! Also, registered in RubyGems with ardecvz@gmail.com
Anyway, is it possible to ask you for code reviews and ideas? Or are you not interested completely in the gem anymore? It would be lonely and sad ;)

**Comment by k0kubun** [comment]
Of course I'll review your code and ideas. But sometimes it can take much time, so this permission is just for your convenience. For example, just now, it's working time for me and can't review this.

**Comment by ardecvz** [comment]
Got it. One more as a reminder:
- [ ] Don't overwrite `~/Library/Application Support/Karabiner` without prompt as it's a really evil thing to people with an existing conf and without backups.

Maybe make a previous version backup automatically or ask for confirmation (at least, for the version without `Generated automatically by Karabiner DSL. Don't change manually.`). Or both.

**Comment by k0kubun** [comment]
>  Now, in order to check for gem's updates you have to visit github as gem doesn't have an easy to use outdated command or notification system.

So it just introduces overhead of one HTTP request. While I've never seen a gem doing such a thing, I think it's acceptable if it's configurable. We should be able to turn off it by karabiner's CLI option or .karabiner's DSL.

> Allow more AVAILABLE_PROPERTIES in items (for example, lastpressedphysicalkey_only).
> Honestly, do it also for similar maps with predefined things as a future-proof solution.

I don't think it's future-proof. Whenever you add DSL like `remap`, it breaks backward compatibility. Of course practically it can be avoided by choosing not-defined property. But it's not just perfect. 

Also for this, it's acceptable if it's configurable, as long as it's not difficult to maintain.

> Rework remap DSL.

Great suggestion. No objection for adding such a feature.

>  Don't overwrite ~/Library/Application Support/Karabiner without prompt as it's a really evil thing to people with an existing conf and without backups.

You mean you want to apply private.xml manually? I agree that it's evil but I couldn't understand why you want the feature. I've never had trouble with that.

The evil functionality can be omitted by adding `-o` option to specify path to print private.xml.

**Comment by ardecvz** [comment]
> So it just introduces overhead of one HTTP request. While I've never seen a gem doing such a thing, I think it's acceptable if it's configurable. We should be able to turn off it by karabiner's CLI option or .karabiner's DSL.

Strange, I've met this functionality a lot of time in ruby utilities. Of course, not in generic gems. For example, see [Travis CLI](https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/command.rb#L140), in the link I've marked the corresponding lines which check the version and warn to STDOUT. One more example is [Heroku CLI](https://github.com/heroku/heroku/blob/master/lib/heroku/updater.rb#L113), I've marked the lines too.

However, I agree it'd add lots of latency to make a request, especially this gem doesn't talk with the Internet normally against my examples which make them every time. Maybe, the better idea is to check for ~/.karabiner or ~/Library/Application Support/Karabiner time of change and if it > 2.weeks ask for a new version. So it introduces one or two in lengthy time slow work.

I'm against any new commands or options - I want to keep the current CLI's simplicity of the gem. Anyway, we should add an option to turn this occasional Internet walks off in DSL: something like root DSL entity `check_for_newer_versions: false` and keep them on by default.

Is it OK?

> I don't think it's future-proof. Whenever you add DSL like remap, it breaks backward compatibility. Of course practically it can be avoided by choosing not-defined property. But it's not just perfect.

Hmmm, although new DSL things may break people configs, we shouldn't choose default Karabiner names for our keywords. It would be real confusing to see `lastpressedphysicalkey_only` as a keyword which do something other than in Karabiner.

So my plan is passing everything down to item without config to turn it off (why would people want it? I don't understand...) and warn them if they use something undefined. On our side, add new keywords to maps, try to keep them up to date and don't use predefined from Karabiner things as it's strange like I've mentioned before. As a result, I want to allow users to use new shiny things from Karabiner without pre-approval which is always late and, honestly, boring.

What do you think?

> Great suggestion. No objection for adding such a feature.

I'll certainly add press, double_press, holding (you may use them together).
But I'm not sure about other ones as I don't use them and they're increasingly complex.
Please see [`this link`](https://pqrs.org/osx/karabiner/xml.html.en#autogen-syntax) and make up good names :)
`__SimultaneousKeyPresses__` = `simultaneous_press to: ''` or `both_press to:''`
`KeyOverlaidModifier` = ?; loggerhead from the rivalry utility ;) use a `press_modifier`
I'm not entirely sure about others.

I also want to keep the current form of remap in work for simple remaps, but I propose to deprecate and then remove `appdef` in favor of generic define block:
```
define do
  app 'HIPCHAT', to: 'com.hipchat.HipChat'
  modifier 'PRIVATE_DANISH_DOLLAR'
  open_url 'Calculator', to: '/Applications/YoruFukurou.app'
  input_source 'MY_DVORAK', to 'com.apple.keylayout.Dvorak'
  device_vendor 'HEWLETT_PACKARD', to: '0x03f0'
  device_product 'MY_HP_KEYBOARD', to: '0x0224'
  # and so on for *def...
end
```
It looks more suitable for all these defines in Karabiner. We may use generic `to:` or specific aliases such as `prefix:`, `equal:`, etc. Or both.

> You mean you want to apply private.xml manually? I agree that it's evil but I couldn't understand why you want the feature. I've never had trouble with that.

No, the change is intended for newcomers:
1) Install the gem
2) Invoke `karabiner dsl` to test the installation
3) Get an empty example ~/.karabiner and your current ~/Library/Application Support/Karabiner configuration overwritten

So my plan is
1) either before every run of the utility make a copy of the current ~/Library/Application Support/Karabiner in ~/Library/Application Support with .backup extension and add `karabiner dsl restore` command to restore the backup. I'm not sure if it'd be useful for newbies as they may invoke the gem twice before started noticing something bad is happening. Also, it shouldn't help for existing users as ~/.karabiner is their canonical path of truth in configuring Karabiner.

2) or add CLI prompt `You're going to overwrite ~/Library/Application Support/Karabiner. Are you sure? Yes/No` in the utility. By the way, we could show it only if their ~/Library/Application Support/Karabiner doesn't have some service line: `Generated automatically by Karabiner DSL. Don't change manually.` I thinks it's the most unintrusive solution to the problem as it doesn't introduce new commands (personally, I don't want to add any new in this roadmap).

I'm sorry for this similar to enterprise dev letter that takes an awful amount of time to read but I don't want to introduce something uncomfortable to the gem.

**Comment by k0kubun** [comment]
> I'm against any new commands or options - I want to keep the current CLI's simplicity of the gem. Anyway, we should add an option to turn this occasional Internet walks off in DSL: something like root DSL entity check_for_newer_versions: false and keep them on by default.
> 
> Is it OK?

If the default is backward-compatible, any changes are acceptable. Please add interface you think it's ok.

> As a result, I want to allow users to use new shiny things from Karabiner without pre-approval which is always late and, honestly, boring.

OK. Please just make sure showing warning message if it's undefined.

> I also want to keep the current form of remap in work for simple remaps, but I propose to deprecate and then remove appdef in favor of generic define block:

Strongly against removing appdef DSL. It's just based on original private.xml and removing appdef increases learning cost of writing .karabiner, especially for users updating private.xml manually so far. I'm not against new DSL itself, please just keep backward compatibility.

> So my plan is ...

+1 for (2). And we should be able to distinguish private.xml manually edited and one generated by karabiner.gem. We shouldn't warn for generated one. Can we do that by adding comment to XML? Otherwise some metadata should be inserted.

<hr>

Again, I have less time to maintain this. Do think by yourself and introduce features you think it's comfortable. You are a new maintainer :)

It doesn't mean I'm not interested in this project but I'm tired of reading many notifications including many other projects' ones. If you want my opinion, please summarize your opinion and reduce the sentences and don't run multiple threads simultaneously. I'm not good at reading English texts. 

I appreciate your interest and effort to this project :+1:
